# Generated by Django 4.2.dev20220624053813 on 2022-06-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('skills', models.ManyToManyField(to='matcherProject.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('skills', models.ManyToManyField(to='matcherProject.skill')),
            ],
        ),
        migrations.RunSQL(
            "CREATE FULLTEXT INDEX full_text_title ON matcherproject_candidate(title)"
        )
    ]
